/* eslint-disable @typescript-eslint/ban-ts-comment */
//@ts-nocheck

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: gbarzu (https://sketchfab.com/gbarzu)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/laptop-asus-rog-zephyrus-g15-made-with-blender-f632acb998334d6d9ecb581b81b1c3eb
Title: Laptop Asus ROG Zephyrus G15 - Made with Blender
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GroupProps } from '@react-three/fiber'

const modelPath = "/assets/3d-models/laptop/scene.gltf"

export const Laptop = (props: GroupProps) => {
  const { nodes, materials } = useGLTF(modelPath, true)
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Cube005_0" position={[0, 0.001, 0]} rotation={[0.029, 0, 0]}>
                <mesh
                  name="Object_4"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_4.geometry}
                  material={materials.InteriorBlack}
                />
                <mesh
                  name="Object_5"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_5.geometry}
                  material={materials.IndicatorLights}
                />
              </group>
              <group name="Cube006_1" position={[0, 0.001, 0]} rotation={[0.029, 0, 0]}>
                <mesh
                  name="Object_7"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_7.geometry}
                  material={materials.InteriorBlack}
                />
              </group>
              <group name="Cube007_2" position={[0, 0.001, 0]} rotation={[0.029, 0, 0]}>
                <mesh
                  name="Object_9"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_9.geometry}
                  material={materials.InteriorBlack}
                />
              </group>
              <group name="Cube008_3" position={[0, 0.001, 0]} rotation={[0.029, 0, 0]}>
                <mesh
                  name="Object_11"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_11.geometry}
                  material={materials.InteriorBlack}
                />
              </group>
              <group name="Cube009_4" position={[-0.17, 0.002, 0.036]} rotation={[0.029, 0, 0]}>
                <mesh
                  name="Object_13"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_13.geometry}
                  material={materials.InteriorBlack}
                />
              </group>
              <group name="Cube010_5" position={[0, 0.002, 0]} rotation={[0.029, 0, 0]}>
                <mesh
                  name="Object_15"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_15.geometry}
                  material={materials.InteriorBlack}
                />
              </group>
              <group
                name="Cube011_6"
                position={[0, -0.001, 0.091]}
                rotation={[-3.113, 0, -Math.PI]}>
                <mesh
                  name="Object_17"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_17.geometry}
                  material={materials.InteriorBlack}
                />
              </group>
              <group name="Cube012_7" position={[0, 0.001, 0]} rotation={[0.029, 0, 0]}>
                <mesh
                  name="Object_19"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_19.geometry}
                  material={materials.InteriorBlack}
                />
              </group>
              <group name="Cube013_8" position={[0, 0.002, -0.015]} rotation={[0.029, 0, 0]}>
                <mesh
                  name="Object_21"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_21.geometry}
                  material={materials.InteriorBlack}
                />
              </group>
              <group name="Cube014_9" position={[0, 0.001, 0]} rotation={[0.029, 0, 0]}>
                <mesh
                  name="Object_23"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_23.geometry}
                  material={materials.InteriorBlack}
                />
              </group>
              <group name="Cube015_10" position={[0, 0.001, 0]} rotation={[0.029, 0, 0]}>
                <mesh
                  name="Object_25"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_25.geometry}
                  material={materials.InteriorBlack}
                />
              </group>
              <group name="Cube016_11" position={[0.001, 0.004, 0]} rotation={[0.029, 0, 0]}>
                <mesh
                  name="Object_27"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_27.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="Bottom001_12"
                position={[-0.001, -0.006, -0.022]}
                rotation={[0.029, 0, 0]}>
                <mesh
                  name="Object_29"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_29.geometry}
                  material={materials.LaptopSurface}
                />
                <mesh
                  name="Object_30"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_30.geometry}
                  material={materials.LaptopSurface}
                />
                <mesh
                  name="Object_31"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_31.geometry}
                  material={materials.LaptopSurface}
                />
                <mesh
                  name="Object_32"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_32.geometry}
                  material={materials.Painted}
                />
              </group>
              <group
                name="Cylinder001_13"
                position={[0, -0.001, -0.008]}
                rotation={[0.029, 0, 0]}
                scale={0.025}>
                <mesh
                  name="Object_34"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_34.geometry}
                  material={materials.InteriorBlack}
                />
              </group>
              <group name="Bottom002_14" position={[0, 0.001, 0]} rotation={[0.029, 0, 0]}>
                <mesh
                  name="Object_36"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_36.geometry}
                  material={materials.LaptopSurface}
                />
              </group>
              <group name="Bottom005_15" position={[0, 0.001, 0]} rotation={[0.029, 0, 0]}>
                <mesh
                  name="Object_38"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_38.geometry}
                  material={materials.SurfaceMetal}
                />
              </group>
              <group name="Plane_16" position={[0, 0.001, 0]}>
                <mesh
                  name="Object_40"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_40.geometry}
                  material={materials.SurfaceMetal}
                />
              </group>
              <group name="Plane001_17" position={[0, 0.001, 0]} rotation={[0.029, Math.PI / 2, 0]}>
                <mesh
                  name="Object_42"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_42.geometry}
                  material={materials.SurfaceMetal}
                />
              </group>
              <group name="Cube031_18" position={[-0.002, 0.007, -0.044]} rotation={[0.029, 0, 0]}>
                <mesh
                  name="Object_44"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_44.geometry}
                  material={materials.Keyboard}
                />
              </group>
              <group name="Cube002_23" position={[0, 0.103, -0.162]}>
                <mesh
                  name="Object_46"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_46.geometry}
                  material={materials.LaptopSurface}
                />
                <mesh
                  name="Object_47"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_47.geometry}
                  material={materials.SurfaceMetal}
                />
                <mesh
                  name="Object_48"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_48.geometry}
                  material={materials.Painted}
                />
                <group name="Cube_19" rotation={[-1.927, 0, 0]}>
                  <mesh
                    name="Object_50"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_50.geometry}
                    material={materials.InteriorBlack}
                  />
                </group>
                <group name="Cube001_20" rotation={[-1.927, 0, 0]}>
                  <mesh
                    name="Object_52"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_52.geometry}
                    material={materials.Logo}
                  />
                </group>
                <group name="Cube003_21" rotation={[-1.927, 0, 0]}>
                  <mesh
                    name="Object_54"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_54.geometry}
                    material={materials.Screen}
                  />
                </group>
                <group name="Cube004_22" rotation={[-1.927, 0, 0]}>
                  <mesh
                    name="Object_56"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_56.geometry}
                    material={materials.LaptopSurface}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(modelPath)