/* eslint-disable @typescript-eslint/ban-ts-comment */
//@ts-nocheck

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Feche Pedroza (https://sketchfab.com/mrfetch)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/scifi-gun-04a9f3ccb5b14dc38a28b27c1916e18e
Title: SciFi Gun
*/



import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GroupProps, useFrame } from '@react-three/fiber'

const modelPath = "/assets/3d-models/pistol/scene.gltf"

export const Pistol = (props: GroupProps) => {
  const { nodes, materials } = useGLTF(modelPath, true)

  const pistolRef = useRef();

  // Apply rotation within the useFrame hook
  useFrame(() => {
    if (pistolRef.current) {
      pistolRef.current.rotation.x += 0.005; // Moderate speed
      pistolRef.current.rotation.y += 0.005;
      pistolRef.current.rotation.z += 0.004; // Optional: Adjust Z separately
    }
  });

  return (
    <group {...props} ref={pistolRef} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Root">
            <group name="BaseMesh">
              <mesh
                name="BaseMesh_1"
                castShadow
                receiveShadow
                geometry={nodes.BaseMesh_1.geometry}
                material={materials.ChumboScyFi}
              />
            </group>
            <group name="Hemi" position={[-5.018, 8.225, 9.525]} rotation={[-0.564, -0.289, 0.424]}>
              <group name="Hemi_1" />
            </group>
            <group
              name="Hemi001"
              position={[3.679, -9.378, -5.222]}
              rotation={[2.242, 0.326, -0.249]}>
              <group name="Hemi001_1" />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(modelPath)