import type { Metadata } from "next";
import "./globals.css";
// import ThemeConfigurator from "@/components/globals/theme-configurator";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="overflow-x-hidden scrollbar">{children}
        {/* <ThemeConfigurator /> */}
      </body>
    </html>
  );
}
